### ISSUE TITLE
module missing

### ISSUE THREAD

**Issue by g1lby** [skx/Device-Osram-Lightify#3]
Hello everyone,

I just downloaded your project to my mac with perl installed on it. When executing ./ol --hub ip.of.my.hub --list this error message shows up and I have no clue where to get this module:

Can't locate Device/Osram/Lightify/Hub.pm in @INC (you may need to install the Device::Osram::Lightify::Hub module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at ./ol line 6.

Would love to hear from you, because this is really a project I've been looking for a long time since I use the Osram Lightify products.

Cheers,
Marc

**Comment by skx** [comment]
> my mac with perl installed on it. When executing ./ol --hub ip.of.my.hub --list this error message shows up and I have no clue where to get this module:

You should have installed the module to the appropriate location by running:

```
  perl Makefile.PL
  make install
```

If you've done that, and are seeing this error then something is wrong that is probably beyond my ability to diagnose remotely - since I'm not 100% familiar with macs.

That said you **might** find that this will work for the moment:

```
 perl -Ilib/ bin/ol --hub ip.of.my.hub --list
```

That uses the `-I` flag to explicitly add the `lib/` directory to the search-path for Perl modules, which should allow the module to be found whether installed or not.

**Comment by g1lby** [comment]
Works both like a charm, except that I needed to run the make install command with sudo privileges.

Thank you so much!
